#!/bin/bash

if  [ $1 = "on" ]; then

   sudo sh -c    "echo 1 > /sys/class/leds/led0/brightness"
fi
if [ $1 = "off" ];
then
 sudo sh -c  "echo  0 > /sys/class/leds/led0/brightness"
fi
if [ $1 = "blink" ];
then
for i in $(eval echo {1..$2})
do
sudo sh -c "echo 1 > /sys/class/leds/led0/brightness"
sleep $3
echo 0
sudo sh -c "echo 0 > /sys/class/leds/led0/brightness"
sleep $3
done
fi
